# Generated by Django 6.1 on 2026-08-31 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100)),
                ('name_ar', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=110, unique=True)),
                ('icon_name', models.CharField(default='check-circle', max_length=50)),
            ],
            options={
                'verbose_name': 'Amenity',
                'verbose_name_plural': 'Amenities',
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('RESIDENTIAL', 'Residential'), ('COMMERCIAL', 'Commercial'), ('LAND', 'Land & Plots')], default='RESIDENTIAL', max_length=20)),
                ('name_en', models.CharField(max_length=80)),
                ('name_ar', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=90, unique=True)),
                ('icon_svg', models.CharField(default='home', help_text='Lucide icon name', max_length=50)),
            ],
            options={
                'verbose_name': 'Property Type',
                'verbose_name_plural': 'Property Types',
                'ordering': ['category', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(db_index=True, editable=False, max_length=30, unique=True)),
                ('title_en', models.CharField(max_length=220)),
                ('title_ar', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True, max_length=260, unique=True)),
                ('description_en', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True)),
                ('purpose', models.CharField(choices=[('RENT', 'For Rent'), ('BUY', 'For Sale'), ('COMMERCIAL', 'Commercial')], default='RENT', max_length=15)),
                ('rent_frequency', models.CharField(blank=True, choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly'), ('DAILY', 'Daily')], default='MONTHLY', max_length=15)),
                ('price', models.DecimalField(decimal_places=3, help_text='Supports KWD 3 decimals & SAR 2 decimals', max_digits=12)),
                ('currency', models.CharField(default='KWD', max_length=5)),
                ('area_sqm', models.DecimalField(decimal_places=2, default=120.0, max_digits=8)),
                ('bedrooms', models.PositiveSmallIntegerField(default=2)),
                ('master_bedrooms', models.PositiveSmallIntegerField(default=1)),
                ('bathrooms', models.PositiveSmallIntegerField(default=2)),
                ('parking_spaces', models.PositiveSmallIntegerField(default=1)),
                ('furnishing', models.CharField(choices=[('UNFURNISHED', 'Unfurnished'), ('SEMI_FURNISHED', 'Semi-Furnished'), ('FULLY_FURNISHED', 'Fully Furnished')], default='UNFURNISHED', max_length=20)),
                ('has_maid_room', models.BooleanField(default=False)),
                ('has_driver_room', models.BooleanField(default=False)),
                ('has_balcony', models.BooleanField(default=False)),
                ('has_sea_view', models.BooleanField(default=False)),
                ('address_line_en', models.CharField(blank=True, max_length=255)),
                ('address_line_ar', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, default=29.3759, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, default=47.9774, max_digits=9)),
                ('tier', models.CharField(choices=[('STANDARD', 'Standard'), ('FEATURED', 'Featured'), ('PREMIUM', 'Premium')], default='STANDARD', max_length=15)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('UNDER_OFFER', 'Under Offer'), ('SOLD_RENTED', 'Sold / Rented'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=15)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('whatsapp_clicks', models.PositiveIntegerField(default=0)),
                ('call_clicks', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='agencies.agency')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='agencies.agent')),
                ('amenities', models.ManyToManyField(blank=True, related_name='properties', to='properties.amenity')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='locations.district')),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='properties.propertytype')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'ordering': ['-tier', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FloorPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Floor Plan Layout', max_length=100)),
                ('image_url', models.URLField(default='https://images.unsplash.com/photo-1574362848149-11496d93a7c7?w=1000')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_plans', to='properties.property')),
            ],
            options={
                'verbose_name': 'Floor Plan',
                'verbose_name_plural': 'Floor Plans',
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(default='https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200')),
                ('caption', models.CharField(blank=True, max_length=150)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'verbose_name': 'Property Image',
                'verbose_name_plural': 'Property Images',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['purpose', 'status', 'price'], name='properties__purpose_de45b4_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['district', 'property_type'], name='properties__distric_2075cc_idx'),
        ),
    ]
