# Generated by Django 6.1 on 2026-08-31 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(help_text='ISO 3166-1 alpha-2 (e.g. KW, SA, AE)', max_length=2, primary_key=True, serialize=False)),
                ('name_en', models.CharField(max_length=100)),
                ('name_ar', models.CharField(max_length=100)),
                ('currency_code', models.CharField(default='KWD', max_length=5)),
                ('currency_symbol_en', models.CharField(default='KD', max_length=10)),
                ('currency_symbol_ar', models.CharField(default='د.ك', max_length=10)),
                ('calling_code', models.CharField(default='+965', max_length=10)),
                ('flag_emoji', models.CharField(default='🇰🇼', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ['display_order', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='Governorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=120)),
                ('name_ar', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='governorates', to='locations.country')),
            ],
            options={
                'verbose_name': 'Governorate / Region',
                'verbose_name_plural': 'Governorates / Regions',
                'ordering': ['name_en'],
                'unique_together': {('country', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=120)),
                ('name_ar', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140)),
                ('governorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='locations.governorate')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'ordering': ['name_en'],
                'unique_together': {('governorate', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=120)),
                ('name_ar', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140)),
                ('latitude', models.DecimalField(decimal_places=6, default=29.3759, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, default=47.9774, max_digits=9)),
                ('zoom_level', models.PositiveSmallIntegerField(default=14)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='locations.city')),
            ],
            options={
                'verbose_name': 'District / Neighborhood',
                'verbose_name_plural': 'Districts / Neighborhoods',
                'ordering': ['name_en'],
                'unique_together': {('city', 'slug')},
            },
        ),
    ]
