# Generated by Django 6.1 on 2026-08-31 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=150)),
                ('name_ar', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('license_no', models.CharField(blank=True, help_text='Ministry / Regulatory Broker License', max_length=60)),
                ('logo_url', models.URLField(blank=True, default='https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=300')),
                ('description_en', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True)),
                ('phone', models.CharField(default='+96522000000', max_length=25)),
                ('whatsapp', models.CharField(default='+96590000000', max_length=25)),
                ('email', models.EmailField(blank=True, default='info@agency.com', max_length=254)),
                ('website', models.URLField(blank=True)),
                ('is_verified', models.BooleanField(default=True)),
                ('rating', models.DecimalField(decimal_places=1, default=4.9, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agencies', to='locations.district')),
            ],
            options={
                'verbose_name': 'Agency',
                'verbose_name_plural': 'Agencies',
                'ordering': ['-is_verified', '-rating', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=120)),
                ('name_ar', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140)),
                ('title_en', models.CharField(default='Senior Property Consultant', max_length=100)),
                ('title_ar', models.CharField(default='مستشار عقاري أول', max_length=100)),
                ('license_no', models.CharField(blank=True, max_length=60)),
                ('avatar_url', models.URLField(blank=True, default='https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300')),
                ('phone', models.CharField(default='+96590000001', max_length=25)),
                ('whatsapp', models.CharField(default='+96590000001', max_length=25)),
                ('email', models.EmailField(blank=True, default='agent@agency.com', max_length=254)),
                ('rating', models.DecimalField(decimal_places=1, default=4.8, max_digits=3)),
                ('is_verified', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='agencies.agency')),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
                'ordering': ['-rating', 'name_en'],
            },
        ),
    ]
